export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd


# Setting PATH for Python 3.11
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:${PATH}"
export PATH

# Otherwise brew doesn't work
eval $(/opt/homebrew/bin/brew shellenv)

source ~/.bashrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/juesato/google-cloud-sdk/path.bash.inc' ]; then . '/Users/juesato/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/juesato/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/juesato/google-cloud-sdk/completion.bash.inc'; fi
